### ISSUE TITLE
[BUG]: Mejorar el hotfix que se hizo al reiniciar sala

### ISSUE THREAD

**Issue by durancristhian** [durancristhian/coronabingo#101]
Explicación: Al reiniciar la sala, no todos los atributos de la sala se están reseteando correctamente. Eso se debe porque solo cambiamos `readyToPlay` a `false`, pero no se están reseteando otros valores como `selectedNumbers`, `soundToPlay` o `confettiType` a sus valores por defecto.

El hotfix consistió en: [clavar un `selectedNumbers: []` en el método `readyToPlay` del admin](https://github.com/durancristhian/coronabingo/blob/master/pages_/room/%5BroomId%5D/admin.tsx#L66)

Lo que se busca hacer: [En este método que es el click del botón confirmar en el modal de reiniciar sala](https://github.com/durancristhian/coronabingo/blob/master/components/Restart.tsx#L17) poner los atributos de la sala que tengan sentido con valores por defecto para que nada de esto pueda volver a pasar. Y obvio que eliminar el hotfix

Mandar el PR al branch `v1.11.0`

**Comment by durancristhian** [comment]
@Grispi te dejo este issue para que lo resuelvas cuando puedas. Si no se entendió algo, preguntame :)

**Comment by Grispi** [comment]
Dale Cris! lo veo y cualquier cosa te pregunto!
