### ISSUE TITLE
[FEATURE] Nueva sección en la home con un video de intro

### ISSUE THREAD

**Issue by durancristhian** [durancristhian/coronabingo#102]
Necesitamos poner en la home una sección con un video que tengo que subir a youtube donde se explica como jugar. Hay un video por idioma.

Creo que lo piola sería que haya un botón con un texto de intro y ese botón abra un modal con el video ahí.

Mandar el PR al branch `v1.11.0`

## Este issue está disponible para ser tomando, mencionarme en un comentario para que te lo pueda asignar

**Comment by fgiuliani** [comment]
Me interesa!

**Comment by durancristhian** [comment]
Bueno, a ver. A considerar:

- Diría que por ahora no pensemos mucho en como va a ser la sección de la home porque capaz la cambie un poco, le agregue más texto o algo así, lo defino y vemos que hacemos para meterlo acá
- Por lo pronto, meté un botón así nomás en algún lugar de la home y ya, que en el onClick muestre nuestro <Modal /> que ya tiene todos los estilos y funcionamiento listo, fijate un ejemplo en otro caso de última, pero no debería ser muy complejo, vas a tener que usar hooks para controlar si está abierto o no, pero insisto, buscás un ejemplo y lo sacás al toque
- Por otro lado, al estar en un entorno de react, meter un iframe o el video tal cual youtube te lo da no va a ser posible. Por eso, sugiero que instales la dependencia [react-youtube](https://www.npmjs.com/package/react-youtube) que agrega un componente que te deja meter un video en base al id y listo. En el sitio de meetup.js lo usamos, buscá en [este archivo](https://raw.githubusercontent.com/meetupjs-ar/meetupjs-ar.github.io/dev/components/Blog/Articles/resena-meetup-julio-2019.mdx) el texto <Youtube /> y vas a ver como lo usamos
- Siguiendo el paso anterior, vamos a tener que importar esas 2 clases CSS que se usan en el ejemplo ese, para garantizar que todo [funcione responsive](https://github.com/meetupjs-ar/meetupjs-ar.github.io/blob/dev/components/Utils/Markdown.css#L104), son esas 2 clases.
- No te olvides que vamos a tener 2 videos, uno por cada idioma, por lo que vamos a tener 2 ids diferentes, nada grave, pero no te olvides

**Comment by durancristhian** [comment]
Gracias por esta nueva colaboración @fgiuliani! Ya fue mergeado el PR, voy a trabajar la estética un poco para que ese video se destaque más pero es un buen primer paso :)
