### ISSUE TITLE
[FEATURE]: Modal con novedades de la versión

### ISSUE THREAD

**Issue by durancristhian** [durancristhian/coronabingo#103]
Estaría bueno que cuando entrás al sitio te muestre en un modal o haya un link para leer sobre las últimas novedades.

Quizás en localStorage se pueda guardar la versión en cada visita y compararla, si cambió, mostrar el modal de esa versión. O algo así, por otro lado, debería salir 1 sola vez, cerrarse o cancelarse. Seguro es algo que muchas apps o sitios hacen. Habría que buscar un ejemplo.

Mandar el PR al branch `v1.11.0`

## Este issue está disponible para ser tomando, mencionarme en un comentario para que te lo pueda asignar

**Comment by leiteszeke** [comment]
Holis @durancristhian vengo a flotar

**Comment by durancristhian** [comment]
Todo tuio @leiteszeke

**Comment by leiteszeke** [comment]
@durancristhian consultas.
Estas novedades de donde van a venir? Firebase, markdown local o algo asi?
La idea que es que las novedades se les muestre solo a los usuarios que ingresaron previamente?

**Comment by durancristhian** [comment]
Hola Eze, no tengo definido mucho pero diría que:

- guardar la versión actual en localStorage
- cuando detectemos un cambio de versión mostrar un modal al cargar la app
- diria que ese modal no tiene nada raro, lo maquetamos a mano y fue

@mateosilguero vos tenés algo en particular para proponer?

**Comment by mateosilguero** [comment]
El modal lo podemos armar a mano, o que se alimente de un "changelog" que armemos aca en GH
