### ISSUE TITLE
[FEATURE] Agregar "https://" al link de la sala que se comparte

### ISSUE THREAD

**Issue by durancristhian** [durancristhian/coronabingo#104]
Hoy en día, compartimos la URL sin el protocolo entonces en WhatsApp no arma el link y hay que copiar y pegar

Creo que window.location.protocol te da el protocolo actual

Mandar el PR al branch `v1.11.0`

## Este issue está disponible para ser tomando, mencionarme en un comentario para que te lo pueda asignar

**Comment by fgiuliani** [comment]
Me interesa!

**Comment by durancristhian** [comment]
Todo tuio
