### ISSUE TITLE
Audio taunts suggestions for the English version

### ISSUE THREAD

**Issue by miparnisari** [durancristhian/coronabingo#35]
- [The Office: This is the worst](https://www.youtube.com/watch?v=cVcn2GB0H6o&feature=youtu.be&t=70)
- [The Office: No God No](https://www.youtube.com/watch?v=CQ_eDE0OMds&feature=youtu.be&t=102)
- [Friends: Let's get ready to rumble](https://www.youtube.com/watch?v=BEv-_4pCCEQ)

**Comment by durancristhian** [comment]
Ya fueron agregados esos audios y deployados a prod :)

Gracias por las sugerencias.
