### ISSUE TITLE
[Refactor]  Crear componente "Anchor"

### ISSUE THREAD

**Issue by durancristhian** [durancristhian/coronabingo#37]
Crear un componente llamado `Anchor` en `/components` que sirva para estandarizar todos los links EXTERNOS que hay en el sitio. Por ejemplo:

<img width="456" alt="Screen Shot 2020-04-06 at 19 56 02" src="https://user-images.githubusercontent.com/4248944/78612843-b0f04d80-7840-11ea-8728-0551eb16ef88.png">

- Mi nombre que lleva a Twitter en el footer
- El link al formulario de feedback en el banner arriba del footer
- El link a Google Hangouts en la home

No recuerdo si hay alguno más.

La idea sería que el componente _renderee_ children y que tenga los estilos que tienen todos esos links mencionados

Luego, reemplazar todos los links visualmente parecidos del sitio por el nuevo componente

Contestar este issue si te interesa hacerlo

**Comment by fgiuliani** [comment]
Yo lo quiero tomar!

**Comment by durancristhian** [comment]
Todo tuyo @fgiuliani :)
