### ISSUE TITLE
[Refactor] Crear componente "Box"

### ISSUE THREAD

**Issue by durancristhian** [durancristhian/coronabingo#38]
Crear un componente llamado "Box" dentro de "/components" que tenga los estilos que tienen todas las cajas blancas del sitio. Ejemplo:

<img width="518" alt="Screen Shot 2020-04-06 at 19 51 46" src="https://user-images.githubusercontent.com/4248944/78612592-1a239100-7840-11ea-8921-860d281f0851.png">

Requerimientos:
- Renderea children
- Tiene igual padding en todos los lados
- Se estira todo lo que puede a lo ancho
- Tiene sombra
- Cualquier otro detalle visual que se considere necesario

Luego, reemplazar todas las cajas blancas del sitio por el nuevo componente

Contestar este issue si te interesa hacerlo

**Comment by fgiuliani** [comment]
Me interesa hacerlo!

**Comment by Grispi** [comment]
Me interesa trabajar en este!

**Comment by durancristhian** [comment]
Listo Gri, todo tuyo 😎
