### ISSUE TITLE
[REFACTOR] Crear componente "Heading"

### ISSUE THREAD

**Issue by durancristhian** [durancristhian/coronabingo#39]
Crear un componente llamado "Heading" dentro de "/components" que tenga los estilos que tienen todos los títulos. Ejemplo:

<img width="276" alt="Screen Shot 2020-04-06 at 19 58 31" src="https://user-images.githubusercontent.com/4248944/78612994-15aba800-7841-11ea-8386-1470d678852b.png">
<img width="183" alt="Screen Shot 2020-04-06 at 19 58 16" src="https://user-images.githubusercontent.com/4248944/78612995-16dcd500-7841-11ea-90bc-c97f29790872.png">

Requerimientos:
- Renderea children
- Recibe como prop el tipo de heading que tiene que dibujar (h1, h2, h3, h4)
- Se estira todo lo que puede a lo ancho
- Tiene los estilos de los títulos, `font-medium`, letra responsive, texto centrado, etc. Que son los estilos que tienen todos los títulos, con mirar un ejemplo se entiende, sino preguntar.
- Cualquier otro detalle visual que se considere necesario

Luego, reemplazar todos los títulos del sitio por el nuevo componente

Contestar este issue si te interesa hacerlo

**Comment by fgiuliani** [comment]
Me interesa hacerlo!

**Comment by Grispi** [comment]
Me interesa hacerlo!

**Comment by durancristhian** [comment]
Todo tuyo! :)
