### ISSUE TITLE
[FEATURE] Hacer que los números de la sección "Últimos números" sea siempre la misma

### ISSUE THREAD

**Issue by durancristhian** [durancristhian/coronabingo#62]
La sección de "Últimos números" genera un array de colores random cuando la página se carga, por lo cual, cambia si la página se refresca, entre tabs y entre las personas que están jugando.

Propongo dejar fijos esos colores, el último número que salió que siempre sea amarillito (`bg-yellow-500`, por ejemplo) y el resto siempre gris (`bg-gray-300`, por ejemplo). De manera de agregar más visibilidad al número que más importa y eliminar este caso que es innecesariamente complejo.

## Este issue está disponible para ser tomando, mencionarme en un comentario para que te lo pueda asignar

**Comment by Grispi** [comment]
Anotame !

**Comment by durancristhian** [comment]
Listo Gri, gracias por coparte.
