### ISSUE TITLE
[REFACTOR] Meter en un context los toast y dejar de usar Message

### ISSUE THREAD

**Issue by durancristhian** [durancristhian/coronabingo#68]
Estaría bueno meter en un context los toasts y que ese componente se encargue de mostrar los mensajes que hoy en día se muestran con el componente Message.

Habría que editarlos visualmente para que sean negros los de information, se puedan apilar si hay más de 1. Junto con esto estaría bueno inhabilitar secciones que disparan acciones como peticiones http. Por ejemplo, al crear una sala, inhabilitar el form, mostrar el Toast de creando sala y luego que se creó satisfactoriamente.

## Este issue está disponible para ser tomando, mencionarme en un comentario para que te lo pueda asignar

**Comment by fgiuliani** [comment]
@durancristhian me interesa este issue!

**Comment by durancristhian** [comment]
Ok, todo tuyo :)

**Comment by durancristhian** [comment]
Este issue está disponible para ser tomado nuevamente

**Comment by durancristhian** [comment]
Done
