### ISSUE TITLE
[BUG]: No se encuentra el player

### ISSUE THREAD

**Issue by durancristhian** [durancristhian/coronabingo#76]
`No document to update: projects/coronabingo-bf16f/databases/(default)/documents/rooms/7XgAXRuSy3uecpYltsg7/players/en1lIkanu7aQOoTn6C6e`

![sentry io_organizations_cristhian-duran_issues_1609961458__project=5171329 query=is%3Aunresolved sort=freq statsPeriod=14d](https://user-images.githubusercontent.com/4248944/79159270-2367ad00-7dae-11ea-9db2-a10ee548315c.png)

**Comment by durancristhian** [comment]
Nada en ese context tiene un `try catch`, creo que arrancaría por ahí

**Comment by durancristhian** [comment]
Ajunto otra cosa, son muchos eventos para pocas personas (arriba a la derecha), por lo que sospecho que tiene que ver con salvar la data de los cartones en cada click

<img width="1680" alt="Screen Shot 2020-04-13 at 18 02 12" src="https://user-images.githubusercontent.com/4248944/79160889-ee108e80-7db0-11ea-8bb2-b6b9efe5d45a.png">

**Comment by mateosilguero** [comment]
Presuntamente arreglado en #81. estar atentos
