### ISSUE TITLE
[BUG]: scrollTo smooth no funciona en algunos devices

### ISSUE THREAD

**Issue by durancristhian** [durancristhian/coronabingo#77]
Probar la solución propuesta en https://gitmemory.com/issue/cypress-io/cypress/2761/500480220 o agregar un polyfill

## Este issue está disponible para ser tomando, mencionarme en un comentario para que te lo pueda asignar

![sentry io_organizations_cristhian-duran_issues_1608760889__project=5171329 query=is%3Aunresolved statsPeriod=14d](https://user-images.githubusercontent.com/4248944/79159794-17c8b600-7daf-11ea-87b5-2123a43bb888.png)

**Comment by fgiuliani** [comment]
@durancristhian puedo echarle un vistazo a este

**Comment by durancristhian** [comment]
Todo tuyo :)
