### ISSUE TITLE
[IDEA] Aplicar cambios sugeridos por Lighthouse

### ISSUE THREAD

**Issue by durancristhian** [durancristhian/coronabingo#88]
Corrí un análisis del sitio en Lighthouse y obtuve [este hermoso reporte](https://lighthouse-dot-webdotdevsite.appspot.com//lh/html?url=https%3A%2F%2Fcoronabingo.now.sh%2F)

¿Qué cosas podemos hacer para mejorar?

Por lo pronto de lo que vi rápidamente:

- Ver como cargar async la librería de los emojis que la usamos para mostrar  _boludeces_ y la tenemos bloqueando el render
- Creo que tenemos un error en el meta viewport

**Comment by leiteszeke** [comment]
Asignamela que le pego una ojeada
